// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: balance.proto

package com.jkramr.demowalletapi.grpc;

public final class Balance {
  private Balance() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BalanceRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BalanceRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 user_id = 1;</code>
     */
    int getUserId();
  }
  /**
   * Protobuf type {@code BalanceRequest}
   */
  public  static final class BalanceRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BalanceRequest)
      BalanceRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BalanceRequest.newBuilder() to construct.
    private BalanceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BalanceRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BalanceRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              userId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jkramr.demowalletapi.grpc.Balance.internal_static_BalanceRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jkramr.demowalletapi.grpc.Balance.internal_static_BalanceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jkramr.demowalletapi.grpc.Balance.BalanceRequest.class, com.jkramr.demowalletapi.grpc.Balance.BalanceRequest.Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>int32 user_id = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0) {
        output.writeInt32(1, userId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jkramr.demowalletapi.grpc.Balance.BalanceRequest)) {
        return super.equals(obj);
      }
      com.jkramr.demowalletapi.grpc.Balance.BalanceRequest other = (com.jkramr.demowalletapi.grpc.Balance.BalanceRequest) obj;

      if (getUserId()
          != other.getUserId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jkramr.demowalletapi.grpc.Balance.BalanceRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.BalanceRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.BalanceRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.BalanceRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.BalanceRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.BalanceRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.BalanceRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.BalanceRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.BalanceRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.BalanceRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.BalanceRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.BalanceRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jkramr.demowalletapi.grpc.Balance.BalanceRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BalanceRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BalanceRequest)
        com.jkramr.demowalletapi.grpc.Balance.BalanceRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jkramr.demowalletapi.grpc.Balance.internal_static_BalanceRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jkramr.demowalletapi.grpc.Balance.internal_static_BalanceRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jkramr.demowalletapi.grpc.Balance.BalanceRequest.class, com.jkramr.demowalletapi.grpc.Balance.BalanceRequest.Builder.class);
      }

      // Construct using com.jkramr.demowalletapi.grpc.Balance.BalanceRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jkramr.demowalletapi.grpc.Balance.internal_static_BalanceRequest_descriptor;
      }

      @java.lang.Override
      public com.jkramr.demowalletapi.grpc.Balance.BalanceRequest getDefaultInstanceForType() {
        return com.jkramr.demowalletapi.grpc.Balance.BalanceRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.jkramr.demowalletapi.grpc.Balance.BalanceRequest build() {
        com.jkramr.demowalletapi.grpc.Balance.BalanceRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.jkramr.demowalletapi.grpc.Balance.BalanceRequest buildPartial() {
        com.jkramr.demowalletapi.grpc.Balance.BalanceRequest result = new com.jkramr.demowalletapi.grpc.Balance.BalanceRequest(this);
        result.userId_ = userId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jkramr.demowalletapi.grpc.Balance.BalanceRequest) {
          return mergeFrom((com.jkramr.demowalletapi.grpc.Balance.BalanceRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jkramr.demowalletapi.grpc.Balance.BalanceRequest other) {
        if (other == com.jkramr.demowalletapi.grpc.Balance.BalanceRequest.getDefaultInstance()) return this;
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jkramr.demowalletapi.grpc.Balance.BalanceRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jkramr.demowalletapi.grpc.Balance.BalanceRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int userId_ ;
      /**
       * <code>int32 user_id = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>int32 user_id = 1;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 user_id = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BalanceRequest)
    }

    // @@protoc_insertion_point(class_scope:BalanceRequest)
    private static final com.jkramr.demowalletapi.grpc.Balance.BalanceRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jkramr.demowalletapi.grpc.Balance.BalanceRequest();
    }

    public static com.jkramr.demowalletapi.grpc.Balance.BalanceRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BalanceRequest>
        PARSER = new com.google.protobuf.AbstractParser<BalanceRequest>() {
      @java.lang.Override
      public BalanceRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BalanceRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BalanceRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BalanceRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.jkramr.demowalletapi.grpc.Balance.BalanceRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WalletBalanceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WalletBalance)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Currency currency = 1;</code>
     */
    int getCurrencyValue();
    /**
     * <code>.Currency currency = 1;</code>
     */
    com.jkramr.demowalletapi.model.Common.Currency getCurrency();

    /**
     * <code>double amount = 2;</code>
     */
    double getAmount();
  }
  /**
   * Protobuf type {@code WalletBalance}
   */
  public  static final class WalletBalance extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WalletBalance)
      WalletBalanceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WalletBalance.newBuilder() to construct.
    private WalletBalance(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WalletBalance() {
      currency_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WalletBalance(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              currency_ = rawValue;
              break;
            }
            case 17: {

              amount_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jkramr.demowalletapi.grpc.Balance.internal_static_WalletBalance_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jkramr.demowalletapi.grpc.Balance.internal_static_WalletBalance_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jkramr.demowalletapi.grpc.Balance.WalletBalance.class, com.jkramr.demowalletapi.grpc.Balance.WalletBalance.Builder.class);
    }

    public static final int CURRENCY_FIELD_NUMBER = 1;
    private int currency_;
    /**
     * <code>.Currency currency = 1;</code>
     */
    public int getCurrencyValue() {
      return currency_;
    }
    /**
     * <code>.Currency currency = 1;</code>
     */
    public com.jkramr.demowalletapi.model.Common.Currency getCurrency() {
      @SuppressWarnings("deprecation")
      com.jkramr.demowalletapi.model.Common.Currency result = com.jkramr.demowalletapi.model.Common.Currency.valueOf(currency_);
      return result == null ? com.jkramr.demowalletapi.model.Common.Currency.UNRECOGNIZED : result;
    }

    public static final int AMOUNT_FIELD_NUMBER = 2;
    private double amount_;
    /**
     * <code>double amount = 2;</code>
     */
    public double getAmount() {
      return amount_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (currency_ != com.jkramr.demowalletapi.model.Common.Currency.EUR.getNumber()) {
        output.writeEnum(1, currency_);
      }
      if (amount_ != 0D) {
        output.writeDouble(2, amount_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (currency_ != com.jkramr.demowalletapi.model.Common.Currency.EUR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, currency_);
      }
      if (amount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, amount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jkramr.demowalletapi.grpc.Balance.WalletBalance)) {
        return super.equals(obj);
      }
      com.jkramr.demowalletapi.grpc.Balance.WalletBalance other = (com.jkramr.demowalletapi.grpc.Balance.WalletBalance) obj;

      if (currency_ != other.currency_) return false;
      if (java.lang.Double.doubleToLongBits(getAmount())
          != java.lang.Double.doubleToLongBits(
              other.getAmount())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + currency_;
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmount()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jkramr.demowalletapi.grpc.Balance.WalletBalance parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.WalletBalance parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.WalletBalance parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.WalletBalance parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.WalletBalance parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.WalletBalance parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.WalletBalance parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.WalletBalance parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.WalletBalance parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.WalletBalance parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.WalletBalance parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.WalletBalance parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jkramr.demowalletapi.grpc.Balance.WalletBalance prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WalletBalance}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WalletBalance)
        com.jkramr.demowalletapi.grpc.Balance.WalletBalanceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jkramr.demowalletapi.grpc.Balance.internal_static_WalletBalance_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jkramr.demowalletapi.grpc.Balance.internal_static_WalletBalance_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jkramr.demowalletapi.grpc.Balance.WalletBalance.class, com.jkramr.demowalletapi.grpc.Balance.WalletBalance.Builder.class);
      }

      // Construct using com.jkramr.demowalletapi.grpc.Balance.WalletBalance.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        currency_ = 0;

        amount_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jkramr.demowalletapi.grpc.Balance.internal_static_WalletBalance_descriptor;
      }

      @java.lang.Override
      public com.jkramr.demowalletapi.grpc.Balance.WalletBalance getDefaultInstanceForType() {
        return com.jkramr.demowalletapi.grpc.Balance.WalletBalance.getDefaultInstance();
      }

      @java.lang.Override
      public com.jkramr.demowalletapi.grpc.Balance.WalletBalance build() {
        com.jkramr.demowalletapi.grpc.Balance.WalletBalance result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.jkramr.demowalletapi.grpc.Balance.WalletBalance buildPartial() {
        com.jkramr.demowalletapi.grpc.Balance.WalletBalance result = new com.jkramr.demowalletapi.grpc.Balance.WalletBalance(this);
        result.currency_ = currency_;
        result.amount_ = amount_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jkramr.demowalletapi.grpc.Balance.WalletBalance) {
          return mergeFrom((com.jkramr.demowalletapi.grpc.Balance.WalletBalance)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jkramr.demowalletapi.grpc.Balance.WalletBalance other) {
        if (other == com.jkramr.demowalletapi.grpc.Balance.WalletBalance.getDefaultInstance()) return this;
        if (other.currency_ != 0) {
          setCurrencyValue(other.getCurrencyValue());
        }
        if (other.getAmount() != 0D) {
          setAmount(other.getAmount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jkramr.demowalletapi.grpc.Balance.WalletBalance parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jkramr.demowalletapi.grpc.Balance.WalletBalance) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int currency_ = 0;
      /**
       * <code>.Currency currency = 1;</code>
       */
      public int getCurrencyValue() {
        return currency_;
      }
      /**
       * <code>.Currency currency = 1;</code>
       */
      public Builder setCurrencyValue(int value) {
        currency_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Currency currency = 1;</code>
       */
      public com.jkramr.demowalletapi.model.Common.Currency getCurrency() {
        @SuppressWarnings("deprecation")
        com.jkramr.demowalletapi.model.Common.Currency result = com.jkramr.demowalletapi.model.Common.Currency.valueOf(currency_);
        return result == null ? com.jkramr.demowalletapi.model.Common.Currency.UNRECOGNIZED : result;
      }
      /**
       * <code>.Currency currency = 1;</code>
       */
      public Builder setCurrency(com.jkramr.demowalletapi.model.Common.Currency value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        currency_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Currency currency = 1;</code>
       */
      public Builder clearCurrency() {
        
        currency_ = 0;
        onChanged();
        return this;
      }

      private double amount_ ;
      /**
       * <code>double amount = 2;</code>
       */
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>double amount = 2;</code>
       */
      public Builder setAmount(double value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double amount = 2;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WalletBalance)
    }

    // @@protoc_insertion_point(class_scope:WalletBalance)
    private static final com.jkramr.demowalletapi.grpc.Balance.WalletBalance DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jkramr.demowalletapi.grpc.Balance.WalletBalance();
    }

    public static com.jkramr.demowalletapi.grpc.Balance.WalletBalance getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WalletBalance>
        PARSER = new com.google.protobuf.AbstractParser<WalletBalance>() {
      @java.lang.Override
      public WalletBalance parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WalletBalance(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WalletBalance> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WalletBalance> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.jkramr.demowalletapi.grpc.Balance.WalletBalance getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BalanceResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BalanceResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .WalletBalance balanceInfo = 1;</code>
     */
    java.util.List<com.jkramr.demowalletapi.grpc.Balance.WalletBalance> 
        getBalanceInfoList();
    /**
     * <code>repeated .WalletBalance balanceInfo = 1;</code>
     */
    com.jkramr.demowalletapi.grpc.Balance.WalletBalance getBalanceInfo(int index);
    /**
     * <code>repeated .WalletBalance balanceInfo = 1;</code>
     */
    int getBalanceInfoCount();
    /**
     * <code>repeated .WalletBalance balanceInfo = 1;</code>
     */
    java.util.List<? extends com.jkramr.demowalletapi.grpc.Balance.WalletBalanceOrBuilder> 
        getBalanceInfoOrBuilderList();
    /**
     * <code>repeated .WalletBalance balanceInfo = 1;</code>
     */
    com.jkramr.demowalletapi.grpc.Balance.WalletBalanceOrBuilder getBalanceInfoOrBuilder(
        int index);

    /**
     * <code>string debugMessage = 2;</code>
     */
    java.lang.String getDebugMessage();
    /**
     * <code>string debugMessage = 2;</code>
     */
    com.google.protobuf.ByteString
        getDebugMessageBytes();
  }
  /**
   * Protobuf type {@code BalanceResponse}
   */
  public  static final class BalanceResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BalanceResponse)
      BalanceResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BalanceResponse.newBuilder() to construct.
    private BalanceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BalanceResponse() {
      balanceInfo_ = java.util.Collections.emptyList();
      debugMessage_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BalanceResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                balanceInfo_ = new java.util.ArrayList<com.jkramr.demowalletapi.grpc.Balance.WalletBalance>();
                mutable_bitField0_ |= 0x00000001;
              }
              balanceInfo_.add(
                  input.readMessage(com.jkramr.demowalletapi.grpc.Balance.WalletBalance.parser(), extensionRegistry));
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              debugMessage_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          balanceInfo_ = java.util.Collections.unmodifiableList(balanceInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jkramr.demowalletapi.grpc.Balance.internal_static_BalanceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jkramr.demowalletapi.grpc.Balance.internal_static_BalanceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jkramr.demowalletapi.grpc.Balance.BalanceResponse.class, com.jkramr.demowalletapi.grpc.Balance.BalanceResponse.Builder.class);
    }

    private int bitField0_;
    public static final int BALANCEINFO_FIELD_NUMBER = 1;
    private java.util.List<com.jkramr.demowalletapi.grpc.Balance.WalletBalance> balanceInfo_;
    /**
     * <code>repeated .WalletBalance balanceInfo = 1;</code>
     */
    public java.util.List<com.jkramr.demowalletapi.grpc.Balance.WalletBalance> getBalanceInfoList() {
      return balanceInfo_;
    }
    /**
     * <code>repeated .WalletBalance balanceInfo = 1;</code>
     */
    public java.util.List<? extends com.jkramr.demowalletapi.grpc.Balance.WalletBalanceOrBuilder> 
        getBalanceInfoOrBuilderList() {
      return balanceInfo_;
    }
    /**
     * <code>repeated .WalletBalance balanceInfo = 1;</code>
     */
    public int getBalanceInfoCount() {
      return balanceInfo_.size();
    }
    /**
     * <code>repeated .WalletBalance balanceInfo = 1;</code>
     */
    public com.jkramr.demowalletapi.grpc.Balance.WalletBalance getBalanceInfo(int index) {
      return balanceInfo_.get(index);
    }
    /**
     * <code>repeated .WalletBalance balanceInfo = 1;</code>
     */
    public com.jkramr.demowalletapi.grpc.Balance.WalletBalanceOrBuilder getBalanceInfoOrBuilder(
        int index) {
      return balanceInfo_.get(index);
    }

    public static final int DEBUGMESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object debugMessage_;
    /**
     * <code>string debugMessage = 2;</code>
     */
    public java.lang.String getDebugMessage() {
      java.lang.Object ref = debugMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        debugMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string debugMessage = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDebugMessageBytes() {
      java.lang.Object ref = debugMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        debugMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < balanceInfo_.size(); i++) {
        output.writeMessage(1, balanceInfo_.get(i));
      }
      if (!getDebugMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, debugMessage_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < balanceInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, balanceInfo_.get(i));
      }
      if (!getDebugMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, debugMessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jkramr.demowalletapi.grpc.Balance.BalanceResponse)) {
        return super.equals(obj);
      }
      com.jkramr.demowalletapi.grpc.Balance.BalanceResponse other = (com.jkramr.demowalletapi.grpc.Balance.BalanceResponse) obj;

      if (!getBalanceInfoList()
          .equals(other.getBalanceInfoList())) return false;
      if (!getDebugMessage()
          .equals(other.getDebugMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getBalanceInfoCount() > 0) {
        hash = (37 * hash) + BALANCEINFO_FIELD_NUMBER;
        hash = (53 * hash) + getBalanceInfoList().hashCode();
      }
      hash = (37 * hash) + DEBUGMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getDebugMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jkramr.demowalletapi.grpc.Balance.BalanceResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.BalanceResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.BalanceResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.BalanceResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.BalanceResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.BalanceResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.BalanceResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.BalanceResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.BalanceResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.BalanceResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.BalanceResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jkramr.demowalletapi.grpc.Balance.BalanceResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jkramr.demowalletapi.grpc.Balance.BalanceResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BalanceResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BalanceResponse)
        com.jkramr.demowalletapi.grpc.Balance.BalanceResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jkramr.demowalletapi.grpc.Balance.internal_static_BalanceResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jkramr.demowalletapi.grpc.Balance.internal_static_BalanceResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jkramr.demowalletapi.grpc.Balance.BalanceResponse.class, com.jkramr.demowalletapi.grpc.Balance.BalanceResponse.Builder.class);
      }

      // Construct using com.jkramr.demowalletapi.grpc.Balance.BalanceResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBalanceInfoFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (balanceInfoBuilder_ == null) {
          balanceInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          balanceInfoBuilder_.clear();
        }
        debugMessage_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jkramr.demowalletapi.grpc.Balance.internal_static_BalanceResponse_descriptor;
      }

      @java.lang.Override
      public com.jkramr.demowalletapi.grpc.Balance.BalanceResponse getDefaultInstanceForType() {
        return com.jkramr.demowalletapi.grpc.Balance.BalanceResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.jkramr.demowalletapi.grpc.Balance.BalanceResponse build() {
        com.jkramr.demowalletapi.grpc.Balance.BalanceResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.jkramr.demowalletapi.grpc.Balance.BalanceResponse buildPartial() {
        com.jkramr.demowalletapi.grpc.Balance.BalanceResponse result = new com.jkramr.demowalletapi.grpc.Balance.BalanceResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (balanceInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            balanceInfo_ = java.util.Collections.unmodifiableList(balanceInfo_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.balanceInfo_ = balanceInfo_;
        } else {
          result.balanceInfo_ = balanceInfoBuilder_.build();
        }
        result.debugMessage_ = debugMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jkramr.demowalletapi.grpc.Balance.BalanceResponse) {
          return mergeFrom((com.jkramr.demowalletapi.grpc.Balance.BalanceResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jkramr.demowalletapi.grpc.Balance.BalanceResponse other) {
        if (other == com.jkramr.demowalletapi.grpc.Balance.BalanceResponse.getDefaultInstance()) return this;
        if (balanceInfoBuilder_ == null) {
          if (!other.balanceInfo_.isEmpty()) {
            if (balanceInfo_.isEmpty()) {
              balanceInfo_ = other.balanceInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBalanceInfoIsMutable();
              balanceInfo_.addAll(other.balanceInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.balanceInfo_.isEmpty()) {
            if (balanceInfoBuilder_.isEmpty()) {
              balanceInfoBuilder_.dispose();
              balanceInfoBuilder_ = null;
              balanceInfo_ = other.balanceInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
              balanceInfoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBalanceInfoFieldBuilder() : null;
            } else {
              balanceInfoBuilder_.addAllMessages(other.balanceInfo_);
            }
          }
        }
        if (!other.getDebugMessage().isEmpty()) {
          debugMessage_ = other.debugMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jkramr.demowalletapi.grpc.Balance.BalanceResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jkramr.demowalletapi.grpc.Balance.BalanceResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.jkramr.demowalletapi.grpc.Balance.WalletBalance> balanceInfo_ =
        java.util.Collections.emptyList();
      private void ensureBalanceInfoIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          balanceInfo_ = new java.util.ArrayList<com.jkramr.demowalletapi.grpc.Balance.WalletBalance>(balanceInfo_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.jkramr.demowalletapi.grpc.Balance.WalletBalance, com.jkramr.demowalletapi.grpc.Balance.WalletBalance.Builder, com.jkramr.demowalletapi.grpc.Balance.WalletBalanceOrBuilder> balanceInfoBuilder_;

      /**
       * <code>repeated .WalletBalance balanceInfo = 1;</code>
       */
      public java.util.List<com.jkramr.demowalletapi.grpc.Balance.WalletBalance> getBalanceInfoList() {
        if (balanceInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(balanceInfo_);
        } else {
          return balanceInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .WalletBalance balanceInfo = 1;</code>
       */
      public int getBalanceInfoCount() {
        if (balanceInfoBuilder_ == null) {
          return balanceInfo_.size();
        } else {
          return balanceInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .WalletBalance balanceInfo = 1;</code>
       */
      public com.jkramr.demowalletapi.grpc.Balance.WalletBalance getBalanceInfo(int index) {
        if (balanceInfoBuilder_ == null) {
          return balanceInfo_.get(index);
        } else {
          return balanceInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .WalletBalance balanceInfo = 1;</code>
       */
      public Builder setBalanceInfo(
          int index, com.jkramr.demowalletapi.grpc.Balance.WalletBalance value) {
        if (balanceInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBalanceInfoIsMutable();
          balanceInfo_.set(index, value);
          onChanged();
        } else {
          balanceInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .WalletBalance balanceInfo = 1;</code>
       */
      public Builder setBalanceInfo(
          int index, com.jkramr.demowalletapi.grpc.Balance.WalletBalance.Builder builderForValue) {
        if (balanceInfoBuilder_ == null) {
          ensureBalanceInfoIsMutable();
          balanceInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          balanceInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .WalletBalance balanceInfo = 1;</code>
       */
      public Builder addBalanceInfo(com.jkramr.demowalletapi.grpc.Balance.WalletBalance value) {
        if (balanceInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBalanceInfoIsMutable();
          balanceInfo_.add(value);
          onChanged();
        } else {
          balanceInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .WalletBalance balanceInfo = 1;</code>
       */
      public Builder addBalanceInfo(
          int index, com.jkramr.demowalletapi.grpc.Balance.WalletBalance value) {
        if (balanceInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBalanceInfoIsMutable();
          balanceInfo_.add(index, value);
          onChanged();
        } else {
          balanceInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .WalletBalance balanceInfo = 1;</code>
       */
      public Builder addBalanceInfo(
          com.jkramr.demowalletapi.grpc.Balance.WalletBalance.Builder builderForValue) {
        if (balanceInfoBuilder_ == null) {
          ensureBalanceInfoIsMutable();
          balanceInfo_.add(builderForValue.build());
          onChanged();
        } else {
          balanceInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .WalletBalance balanceInfo = 1;</code>
       */
      public Builder addBalanceInfo(
          int index, com.jkramr.demowalletapi.grpc.Balance.WalletBalance.Builder builderForValue) {
        if (balanceInfoBuilder_ == null) {
          ensureBalanceInfoIsMutable();
          balanceInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          balanceInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .WalletBalance balanceInfo = 1;</code>
       */
      public Builder addAllBalanceInfo(
          java.lang.Iterable<? extends com.jkramr.demowalletapi.grpc.Balance.WalletBalance> values) {
        if (balanceInfoBuilder_ == null) {
          ensureBalanceInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, balanceInfo_);
          onChanged();
        } else {
          balanceInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .WalletBalance balanceInfo = 1;</code>
       */
      public Builder clearBalanceInfo() {
        if (balanceInfoBuilder_ == null) {
          balanceInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          balanceInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .WalletBalance balanceInfo = 1;</code>
       */
      public Builder removeBalanceInfo(int index) {
        if (balanceInfoBuilder_ == null) {
          ensureBalanceInfoIsMutable();
          balanceInfo_.remove(index);
          onChanged();
        } else {
          balanceInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .WalletBalance balanceInfo = 1;</code>
       */
      public com.jkramr.demowalletapi.grpc.Balance.WalletBalance.Builder getBalanceInfoBuilder(
          int index) {
        return getBalanceInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .WalletBalance balanceInfo = 1;</code>
       */
      public com.jkramr.demowalletapi.grpc.Balance.WalletBalanceOrBuilder getBalanceInfoOrBuilder(
          int index) {
        if (balanceInfoBuilder_ == null) {
          return balanceInfo_.get(index);  } else {
          return balanceInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .WalletBalance balanceInfo = 1;</code>
       */
      public java.util.List<? extends com.jkramr.demowalletapi.grpc.Balance.WalletBalanceOrBuilder> 
           getBalanceInfoOrBuilderList() {
        if (balanceInfoBuilder_ != null) {
          return balanceInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(balanceInfo_);
        }
      }
      /**
       * <code>repeated .WalletBalance balanceInfo = 1;</code>
       */
      public com.jkramr.demowalletapi.grpc.Balance.WalletBalance.Builder addBalanceInfoBuilder() {
        return getBalanceInfoFieldBuilder().addBuilder(
            com.jkramr.demowalletapi.grpc.Balance.WalletBalance.getDefaultInstance());
      }
      /**
       * <code>repeated .WalletBalance balanceInfo = 1;</code>
       */
      public com.jkramr.demowalletapi.grpc.Balance.WalletBalance.Builder addBalanceInfoBuilder(
          int index) {
        return getBalanceInfoFieldBuilder().addBuilder(
            index, com.jkramr.demowalletapi.grpc.Balance.WalletBalance.getDefaultInstance());
      }
      /**
       * <code>repeated .WalletBalance balanceInfo = 1;</code>
       */
      public java.util.List<com.jkramr.demowalletapi.grpc.Balance.WalletBalance.Builder> 
           getBalanceInfoBuilderList() {
        return getBalanceInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.jkramr.demowalletapi.grpc.Balance.WalletBalance, com.jkramr.demowalletapi.grpc.Balance.WalletBalance.Builder, com.jkramr.demowalletapi.grpc.Balance.WalletBalanceOrBuilder> 
          getBalanceInfoFieldBuilder() {
        if (balanceInfoBuilder_ == null) {
          balanceInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.jkramr.demowalletapi.grpc.Balance.WalletBalance, com.jkramr.demowalletapi.grpc.Balance.WalletBalance.Builder, com.jkramr.demowalletapi.grpc.Balance.WalletBalanceOrBuilder>(
                  balanceInfo_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          balanceInfo_ = null;
        }
        return balanceInfoBuilder_;
      }

      private java.lang.Object debugMessage_ = "";
      /**
       * <code>string debugMessage = 2;</code>
       */
      public java.lang.String getDebugMessage() {
        java.lang.Object ref = debugMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          debugMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string debugMessage = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDebugMessageBytes() {
        java.lang.Object ref = debugMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          debugMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string debugMessage = 2;</code>
       */
      public Builder setDebugMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        debugMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string debugMessage = 2;</code>
       */
      public Builder clearDebugMessage() {
        
        debugMessage_ = getDefaultInstance().getDebugMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string debugMessage = 2;</code>
       */
      public Builder setDebugMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        debugMessage_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BalanceResponse)
    }

    // @@protoc_insertion_point(class_scope:BalanceResponse)
    private static final com.jkramr.demowalletapi.grpc.Balance.BalanceResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jkramr.demowalletapi.grpc.Balance.BalanceResponse();
    }

    public static com.jkramr.demowalletapi.grpc.Balance.BalanceResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BalanceResponse>
        PARSER = new com.google.protobuf.AbstractParser<BalanceResponse>() {
      @java.lang.Override
      public BalanceResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BalanceResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BalanceResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BalanceResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.jkramr.demowalletapi.grpc.Balance.BalanceResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BalanceRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BalanceRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WalletBalance_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WalletBalance_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BalanceResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BalanceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rbalance.proto\032\014common.proto\"!\n\016Balance" +
      "Request\022\017\n\007user_id\030\001 \001(\005\"<\n\rWalletBalanc" +
      "e\022\033\n\010currency\030\001 \001(\0162\t.Currency\022\016\n\006amount" +
      "\030\002 \001(\001\"L\n\017BalanceResponse\022#\n\013balanceInfo" +
      "\030\001 \003(\0132\016.WalletBalance\022\024\n\014debugMessage\030\002" +
      " \001(\t2C\n\016BalanceService\0221\n\nGetBalance\022\017.B" +
      "alanceRequest\032\020.BalanceResponse\"\000B\037\n\035com" +
      ".jkramr.demowalletapi.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.jkramr.demowalletapi.model.Common.getDescriptor(),
        }, assigner);
    internal_static_BalanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BalanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BalanceRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_WalletBalance_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WalletBalance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WalletBalance_descriptor,
        new java.lang.String[] { "Currency", "Amount", });
    internal_static_BalanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_BalanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BalanceResponse_descriptor,
        new java.lang.String[] { "BalanceInfo", "DebugMessage", });
    com.jkramr.demowalletapi.model.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
