// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: deposit.proto

package com.jkramr.demowalletapi.grpc;

public final class Deposit {
  private Deposit() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DepositRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DepositRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 user_id = 1;</code>
     */
    int getUserId();

    /**
     * <code>double amount = 2;</code>
     */
    double getAmount();

    /**
     * <code>.Currency currency = 3;</code>
     */
    int getCurrencyValue();
    /**
     * <code>.Currency currency = 3;</code>
     */
    com.jkramr.demowalletapi.model.Common.Currency getCurrency();
  }
  /**
   * Protobuf type {@code DepositRequest}
   */
  public  static final class DepositRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DepositRequest)
      DepositRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DepositRequest.newBuilder() to construct.
    private DepositRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DepositRequest() {
      currency_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DepositRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              userId_ = input.readInt32();
              break;
            }
            case 17: {

              amount_ = input.readDouble();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              currency_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jkramr.demowalletapi.grpc.Deposit.internal_static_DepositRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jkramr.demowalletapi.grpc.Deposit.internal_static_DepositRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jkramr.demowalletapi.grpc.Deposit.DepositRequest.class, com.jkramr.demowalletapi.grpc.Deposit.DepositRequest.Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>int32 user_id = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int AMOUNT_FIELD_NUMBER = 2;
    private double amount_;
    /**
     * <code>double amount = 2;</code>
     */
    public double getAmount() {
      return amount_;
    }

    public static final int CURRENCY_FIELD_NUMBER = 3;
    private int currency_;
    /**
     * <code>.Currency currency = 3;</code>
     */
    public int getCurrencyValue() {
      return currency_;
    }
    /**
     * <code>.Currency currency = 3;</code>
     */
    public com.jkramr.demowalletapi.model.Common.Currency getCurrency() {
      @SuppressWarnings("deprecation")
      com.jkramr.demowalletapi.model.Common.Currency result = com.jkramr.demowalletapi.model.Common.Currency.valueOf(currency_);
      return result == null ? com.jkramr.demowalletapi.model.Common.Currency.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0) {
        output.writeInt32(1, userId_);
      }
      if (amount_ != 0D) {
        output.writeDouble(2, amount_);
      }
      if (currency_ != com.jkramr.demowalletapi.model.Common.Currency.EUR.getNumber()) {
        output.writeEnum(3, currency_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (amount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, amount_);
      }
      if (currency_ != com.jkramr.demowalletapi.model.Common.Currency.EUR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, currency_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jkramr.demowalletapi.grpc.Deposit.DepositRequest)) {
        return super.equals(obj);
      }
      com.jkramr.demowalletapi.grpc.Deposit.DepositRequest other = (com.jkramr.demowalletapi.grpc.Deposit.DepositRequest) obj;

      if (getUserId()
          != other.getUserId()) return false;
      if (java.lang.Double.doubleToLongBits(getAmount())
          != java.lang.Double.doubleToLongBits(
              other.getAmount())) return false;
      if (currency_ != other.currency_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmount()));
      hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + currency_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jkramr.demowalletapi.grpc.Deposit.DepositRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jkramr.demowalletapi.grpc.Deposit.DepositRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Deposit.DepositRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jkramr.demowalletapi.grpc.Deposit.DepositRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Deposit.DepositRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jkramr.demowalletapi.grpc.Deposit.DepositRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Deposit.DepositRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jkramr.demowalletapi.grpc.Deposit.DepositRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Deposit.DepositRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jkramr.demowalletapi.grpc.Deposit.DepositRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Deposit.DepositRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jkramr.demowalletapi.grpc.Deposit.DepositRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jkramr.demowalletapi.grpc.Deposit.DepositRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DepositRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DepositRequest)
        com.jkramr.demowalletapi.grpc.Deposit.DepositRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jkramr.demowalletapi.grpc.Deposit.internal_static_DepositRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jkramr.demowalletapi.grpc.Deposit.internal_static_DepositRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jkramr.demowalletapi.grpc.Deposit.DepositRequest.class, com.jkramr.demowalletapi.grpc.Deposit.DepositRequest.Builder.class);
      }

      // Construct using com.jkramr.demowalletapi.grpc.Deposit.DepositRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = 0;

        amount_ = 0D;

        currency_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jkramr.demowalletapi.grpc.Deposit.internal_static_DepositRequest_descriptor;
      }

      @java.lang.Override
      public com.jkramr.demowalletapi.grpc.Deposit.DepositRequest getDefaultInstanceForType() {
        return com.jkramr.demowalletapi.grpc.Deposit.DepositRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.jkramr.demowalletapi.grpc.Deposit.DepositRequest build() {
        com.jkramr.demowalletapi.grpc.Deposit.DepositRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.jkramr.demowalletapi.grpc.Deposit.DepositRequest buildPartial() {
        com.jkramr.demowalletapi.grpc.Deposit.DepositRequest result = new com.jkramr.demowalletapi.grpc.Deposit.DepositRequest(this);
        result.userId_ = userId_;
        result.amount_ = amount_;
        result.currency_ = currency_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jkramr.demowalletapi.grpc.Deposit.DepositRequest) {
          return mergeFrom((com.jkramr.demowalletapi.grpc.Deposit.DepositRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jkramr.demowalletapi.grpc.Deposit.DepositRequest other) {
        if (other == com.jkramr.demowalletapi.grpc.Deposit.DepositRequest.getDefaultInstance()) return this;
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (other.getAmount() != 0D) {
          setAmount(other.getAmount());
        }
        if (other.currency_ != 0) {
          setCurrencyValue(other.getCurrencyValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jkramr.demowalletapi.grpc.Deposit.DepositRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jkramr.demowalletapi.grpc.Deposit.DepositRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int userId_ ;
      /**
       * <code>int32 user_id = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>int32 user_id = 1;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 user_id = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private double amount_ ;
      /**
       * <code>double amount = 2;</code>
       */
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>double amount = 2;</code>
       */
      public Builder setAmount(double value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double amount = 2;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0D;
        onChanged();
        return this;
      }

      private int currency_ = 0;
      /**
       * <code>.Currency currency = 3;</code>
       */
      public int getCurrencyValue() {
        return currency_;
      }
      /**
       * <code>.Currency currency = 3;</code>
       */
      public Builder setCurrencyValue(int value) {
        currency_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Currency currency = 3;</code>
       */
      public com.jkramr.demowalletapi.model.Common.Currency getCurrency() {
        @SuppressWarnings("deprecation")
        com.jkramr.demowalletapi.model.Common.Currency result = com.jkramr.demowalletapi.model.Common.Currency.valueOf(currency_);
        return result == null ? com.jkramr.demowalletapi.model.Common.Currency.UNRECOGNIZED : result;
      }
      /**
       * <code>.Currency currency = 3;</code>
       */
      public Builder setCurrency(com.jkramr.demowalletapi.model.Common.Currency value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        currency_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Currency currency = 3;</code>
       */
      public Builder clearCurrency() {
        
        currency_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DepositRequest)
    }

    // @@protoc_insertion_point(class_scope:DepositRequest)
    private static final com.jkramr.demowalletapi.grpc.Deposit.DepositRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jkramr.demowalletapi.grpc.Deposit.DepositRequest();
    }

    public static com.jkramr.demowalletapi.grpc.Deposit.DepositRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DepositRequest>
        PARSER = new com.google.protobuf.AbstractParser<DepositRequest>() {
      @java.lang.Override
      public DepositRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DepositRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DepositRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DepositRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.jkramr.demowalletapi.grpc.Deposit.DepositRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DepositResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DepositResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.DepositResponse.Error error = 1;</code>
     */
    int getErrorValue();
    /**
     * <code>.DepositResponse.Error error = 1;</code>
     */
    com.jkramr.demowalletapi.grpc.Deposit.DepositResponse.Error getError();

    /**
     * <code>string debugMessage = 2;</code>
     */
    java.lang.String getDebugMessage();
    /**
     * <code>string debugMessage = 2;</code>
     */
    com.google.protobuf.ByteString
        getDebugMessageBytes();
  }
  /**
   * Protobuf type {@code DepositResponse}
   */
  public  static final class DepositResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DepositResponse)
      DepositResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DepositResponse.newBuilder() to construct.
    private DepositResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DepositResponse() {
      error_ = 0;
      debugMessage_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DepositResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              error_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              debugMessage_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jkramr.demowalletapi.grpc.Deposit.internal_static_DepositResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jkramr.demowalletapi.grpc.Deposit.internal_static_DepositResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jkramr.demowalletapi.grpc.Deposit.DepositResponse.class, com.jkramr.demowalletapi.grpc.Deposit.DepositResponse.Builder.class);
    }

    /**
     * Protobuf enum {@code DepositResponse.Error}
     */
    public enum Error
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN_CURRENCY = 0;</code>
       */
      UNKNOWN_CURRENCY(0),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN_CURRENCY = 0;</code>
       */
      public static final int UNKNOWN_CURRENCY_VALUE = 0;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Error valueOf(int value) {
        return forNumber(value);
      }

      public static Error forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN_CURRENCY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Error>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Error> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Error>() {
              public Error findValueByNumber(int number) {
                return Error.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.jkramr.demowalletapi.grpc.Deposit.DepositResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final Error[] VALUES = values();

      public static Error valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Error(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:DepositResponse.Error)
    }

    public static final int ERROR_FIELD_NUMBER = 1;
    private int error_;
    /**
     * <code>.DepositResponse.Error error = 1;</code>
     */
    public int getErrorValue() {
      return error_;
    }
    /**
     * <code>.DepositResponse.Error error = 1;</code>
     */
    public com.jkramr.demowalletapi.grpc.Deposit.DepositResponse.Error getError() {
      @SuppressWarnings("deprecation")
      com.jkramr.demowalletapi.grpc.Deposit.DepositResponse.Error result = com.jkramr.demowalletapi.grpc.Deposit.DepositResponse.Error.valueOf(error_);
      return result == null ? com.jkramr.demowalletapi.grpc.Deposit.DepositResponse.Error.UNRECOGNIZED : result;
    }

    public static final int DEBUGMESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object debugMessage_;
    /**
     * <code>string debugMessage = 2;</code>
     */
    public java.lang.String getDebugMessage() {
      java.lang.Object ref = debugMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        debugMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string debugMessage = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDebugMessageBytes() {
      java.lang.Object ref = debugMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        debugMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (error_ != com.jkramr.demowalletapi.grpc.Deposit.DepositResponse.Error.UNKNOWN_CURRENCY.getNumber()) {
        output.writeEnum(1, error_);
      }
      if (!getDebugMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, debugMessage_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (error_ != com.jkramr.demowalletapi.grpc.Deposit.DepositResponse.Error.UNKNOWN_CURRENCY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, error_);
      }
      if (!getDebugMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, debugMessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jkramr.demowalletapi.grpc.Deposit.DepositResponse)) {
        return super.equals(obj);
      }
      com.jkramr.demowalletapi.grpc.Deposit.DepositResponse other = (com.jkramr.demowalletapi.grpc.Deposit.DepositResponse) obj;

      if (error_ != other.error_) return false;
      if (!getDebugMessage()
          .equals(other.getDebugMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + error_;
      hash = (37 * hash) + DEBUGMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getDebugMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jkramr.demowalletapi.grpc.Deposit.DepositResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jkramr.demowalletapi.grpc.Deposit.DepositResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Deposit.DepositResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jkramr.demowalletapi.grpc.Deposit.DepositResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Deposit.DepositResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jkramr.demowalletapi.grpc.Deposit.DepositResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Deposit.DepositResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jkramr.demowalletapi.grpc.Deposit.DepositResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Deposit.DepositResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jkramr.demowalletapi.grpc.Deposit.DepositResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jkramr.demowalletapi.grpc.Deposit.DepositResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jkramr.demowalletapi.grpc.Deposit.DepositResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jkramr.demowalletapi.grpc.Deposit.DepositResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DepositResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DepositResponse)
        com.jkramr.demowalletapi.grpc.Deposit.DepositResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jkramr.demowalletapi.grpc.Deposit.internal_static_DepositResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jkramr.demowalletapi.grpc.Deposit.internal_static_DepositResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jkramr.demowalletapi.grpc.Deposit.DepositResponse.class, com.jkramr.demowalletapi.grpc.Deposit.DepositResponse.Builder.class);
      }

      // Construct using com.jkramr.demowalletapi.grpc.Deposit.DepositResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        error_ = 0;

        debugMessage_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jkramr.demowalletapi.grpc.Deposit.internal_static_DepositResponse_descriptor;
      }

      @java.lang.Override
      public com.jkramr.demowalletapi.grpc.Deposit.DepositResponse getDefaultInstanceForType() {
        return com.jkramr.demowalletapi.grpc.Deposit.DepositResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.jkramr.demowalletapi.grpc.Deposit.DepositResponse build() {
        com.jkramr.demowalletapi.grpc.Deposit.DepositResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.jkramr.demowalletapi.grpc.Deposit.DepositResponse buildPartial() {
        com.jkramr.demowalletapi.grpc.Deposit.DepositResponse result = new com.jkramr.demowalletapi.grpc.Deposit.DepositResponse(this);
        result.error_ = error_;
        result.debugMessage_ = debugMessage_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jkramr.demowalletapi.grpc.Deposit.DepositResponse) {
          return mergeFrom((com.jkramr.demowalletapi.grpc.Deposit.DepositResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jkramr.demowalletapi.grpc.Deposit.DepositResponse other) {
        if (other == com.jkramr.demowalletapi.grpc.Deposit.DepositResponse.getDefaultInstance()) return this;
        if (other.error_ != 0) {
          setErrorValue(other.getErrorValue());
        }
        if (!other.getDebugMessage().isEmpty()) {
          debugMessage_ = other.debugMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jkramr.demowalletapi.grpc.Deposit.DepositResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jkramr.demowalletapi.grpc.Deposit.DepositResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int error_ = 0;
      /**
       * <code>.DepositResponse.Error error = 1;</code>
       */
      public int getErrorValue() {
        return error_;
      }
      /**
       * <code>.DepositResponse.Error error = 1;</code>
       */
      public Builder setErrorValue(int value) {
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.DepositResponse.Error error = 1;</code>
       */
      public com.jkramr.demowalletapi.grpc.Deposit.DepositResponse.Error getError() {
        @SuppressWarnings("deprecation")
        com.jkramr.demowalletapi.grpc.Deposit.DepositResponse.Error result = com.jkramr.demowalletapi.grpc.Deposit.DepositResponse.Error.valueOf(error_);
        return result == null ? com.jkramr.demowalletapi.grpc.Deposit.DepositResponse.Error.UNRECOGNIZED : result;
      }
      /**
       * <code>.DepositResponse.Error error = 1;</code>
       */
      public Builder setError(com.jkramr.demowalletapi.grpc.Deposit.DepositResponse.Error value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        error_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.DepositResponse.Error error = 1;</code>
       */
      public Builder clearError() {
        
        error_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object debugMessage_ = "";
      /**
       * <code>string debugMessage = 2;</code>
       */
      public java.lang.String getDebugMessage() {
        java.lang.Object ref = debugMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          debugMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string debugMessage = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDebugMessageBytes() {
        java.lang.Object ref = debugMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          debugMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string debugMessage = 2;</code>
       */
      public Builder setDebugMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        debugMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string debugMessage = 2;</code>
       */
      public Builder clearDebugMessage() {
        
        debugMessage_ = getDefaultInstance().getDebugMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string debugMessage = 2;</code>
       */
      public Builder setDebugMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        debugMessage_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DepositResponse)
    }

    // @@protoc_insertion_point(class_scope:DepositResponse)
    private static final com.jkramr.demowalletapi.grpc.Deposit.DepositResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jkramr.demowalletapi.grpc.Deposit.DepositResponse();
    }

    public static com.jkramr.demowalletapi.grpc.Deposit.DepositResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DepositResponse>
        PARSER = new com.google.protobuf.AbstractParser<DepositResponse>() {
      @java.lang.Override
      public DepositResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DepositResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DepositResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DepositResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.jkramr.demowalletapi.grpc.Deposit.DepositResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DepositRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DepositRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DepositResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DepositResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rdeposit.proto\032\014common.proto\"N\n\016Deposit" +
      "Request\022\017\n\007user_id\030\001 \001(\005\022\016\n\006amount\030\002 \001(\001" +
      "\022\033\n\010currency\030\003 \001(\0162\t.Currency\"m\n\017Deposit" +
      "Response\022%\n\005error\030\001 \001(\0162\026.DepositRespons" +
      "e.Error\022\024\n\014debugMessage\030\002 \001(\t\"\035\n\005Error\022\024" +
      "\n\020UNKNOWN_CURRENCY\020\0002E\n\016DepositService\0223" +
      "\n\014DepositFunds\022\017.DepositRequest\032\020.Deposi" +
      "tResponse\"\000B\037\n\035com.jkramr.demowalletapi." +
      "grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.jkramr.demowalletapi.model.Common.getDescriptor(),
        }, assigner);
    internal_static_DepositRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DepositRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DepositRequest_descriptor,
        new java.lang.String[] { "UserId", "Amount", "Currency", });
    internal_static_DepositResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DepositResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DepositResponse_descriptor,
        new java.lang.String[] { "Error", "DebugMessage", });
    com.jkramr.demowalletapi.model.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
